//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactQuality.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQDET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CQDET()
        {
            this.CQKPIGrades = new HashSet<CQKPIGrade>();
          OnCreated();
        }
    
    	partial void OnCreated();
    
        public int CQDETID { get; set; }
        public Nullable<int> CQHDRID { get; set; }
        public int CQCID { get; set; }
        public Nullable<decimal> GCGrade { get; set; }
        public Nullable<decimal> CEGrade { get; set; }
        public Nullable<decimal> CCGrade { get; set; }
        public Nullable<decimal> CHGrade { get; set; }
        public Nullable<decimal> PKGrade { get; set; }
        public Nullable<decimal> SFGrade { get; set; }
        public Nullable<decimal> ERGrade { get; set; }
        public Nullable<decimal> SSGrade { get; set; }
        public Nullable<System.DateTime> CQEvalDate { get; set; }
        public string CQEvaluator { get; set; }
        public string CQTitle { get; set; }
        public string CQRecording { get; set; }
        public string EvaluatorNote { get; set; }
    
        public virtual CQChannel CQChannel { get; set; }
        public virtual CQHDR CQHDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CQKPIGrade> CQKPIGrades { get; set; }
    }
}
