//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactQuality.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQHDR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CQHDR()
        {
            this.CQDETs = new HashSet<CQDET>();
          OnCreated();
        }
    
    	partial void OnCreated();
    
        public int CQHDRID { get; set; }
        public string AgentLogin { get; set; }
        public Nullable<int> CQYear { get; set; }
        public Nullable<int> CQPID { get; set; }
    
        public virtual CQPeriod CQPeriod { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CQDET> CQDETs { get; set; }
    }
}
