//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactQuality.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQKPIGrade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CQKPIGrade()
        {
          OnCreated();
        }
    
    	partial void OnCreated();
    
        public int CQKPIGID { get; set; }
        public int CQDETID { get; set; }
        public int CQKPIID { get; set; }
        public Nullable<int> CQGrade { get; set; }
        public string EvaluatorRemark { get; set; }
    
        public virtual CQKPI CQKPI { get; set; }
        public virtual CQDET CQDET { get; set; }
    }
}
