//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactQuality.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQKPI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CQKPI()
        {
            this.CQKPIGrades = new HashSet<CQKPIGrade>();
            this.CQKPIChannels = new HashSet<CQKPIChannel>();
          OnCreated();
        }
    
    	partial void OnCreated();
    
        public int CQKPIID { get; set; }
        public int CQGKPIID { get; set; }
        public string CQKPIName { get; set; }
        public string CQKPIType { get; set; }
        public Nullable<int> CQKPIMaxGrade { get; set; }
        public string RadioBtnID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CQKPIGrade> CQKPIGrades { get; set; }
        public virtual CQGKPI CQGKPI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CQKPIChannel> CQKPIChannels { get; set; }
    }
}
