//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactQuality.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CQContext : DbContext
    {
        public CQContext()
            : base("name=CQContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CQChannel> CQChannels { get; set; }
        public virtual DbSet<CQHDR> CQHDRs { get; set; }
        public virtual DbSet<CQPeriod> CQPeriods { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<CQKPIGrade> CQKPIGrades { get; set; }
        public virtual DbSet<CQKPI> CQKPIs { get; set; }
        public virtual DbSet<CQDET> CQDETs { get; set; }
        public virtual DbSet<CQGKPI> CQGKPIs { get; set; }
        public virtual DbSet<Competency> Competencies { get; set; }
        public virtual DbSet<CQGKPIChannel> CQGKPIChannels { get; set; }
        public virtual DbSet<CQKPIChannel> CQKPIChannels { get; set; }
        public virtual DbSet<CQTNeed> CQTNeeds { get; set; }
    }
}
