//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactQuality.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CQPeriod()
        {
            this.CQHDRs = new HashSet<CQHDR>();
          OnCreated();
        }
    
    	partial void OnCreated();
    
        public int CQPID { get; set; }
        public string CQPeriodName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CQHDR> CQHDRs { get; set; }
    }
}
