//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactQuality.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CQTNeed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CQTNeed()
        {
          OnCreated();
        }
    
    	partial void OnCreated();
    
        public int TNID { get; set; }
        public Nullable<int> CompID { get; set; }
        public string AgentLogin { get; set; }
        public string TNLevel { get; set; }
        public string TNStatus { get; set; }
    
        public virtual Competency Competency { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
